<a href="https://colab.research.google.com/github/anaiy2004/ALI-Risk-Prediction/blob/main/Skin_Disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount("/content/gdrive")
%cd gdrive/My Drive/project_folder
!git clone "https://github.com/siddrrsh/DermaDetect.git"

Mounted at /content/gdrive
/content/gdrive/My Drive/project_folder
fatal: destination path 'DermaDetect' already exists and is not an empty directory.


In [1]:
!git clone "https://github.com/siddrrsh/DermaDetect.git"

fatal: destination path 'DermaDetect' already exists and is not an empty directory.


In [2]:
import PIL
from PIL import Image
import numpy as np
def jpegTo3dVector(img_url):
  samp_img = Image.open(img_url)
  samp_img = samp_img.resize((2000,2000))
  I = np.asarray(samp_img)
  return I

In [3]:
import os
X = list()
y = list()
counter = -1
dir = "/content/gdrive/MyDrive/project_folder/DermaDetect/dataset"
#dir = "DermaDetect/dataset"
for disease in os.listdir(dir):
  directory = "/content/gdrive/MyDrive/project_folder/DermaDetect/dataset/" + disease
  #directory = "DermaDetect/dataset/" + disease
  counter += 1
  for filename in os.listdir(directory):
      f = os.path.join(directory, filename)
      if os.path.isfile(f):
          arr = jpegTo3dVector(f)
          if(arr.shape[2] == 3):
            X.append(arr)
            y.append(counter)

In [4]:
#one-hot encoding the labels
from sklearn.preprocessing import OneHotEncoder
from array import array
enc = OneHotEncoder()
values = np.array(y)
values = values.reshape(-1,1)
label_encoder = OneHotEncoder()
encoded = label_encoder.fit_transform(values).todense()
y = np.squeeze(np.asarray(encoded))
print(y)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [6]:
X_train[10].shape

(2000, 2000, 3)

In [7]:
y = np.array(y)
y.shape

(151, 12)

In [8]:
y_train[0]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
X_train = np.array(X_train)
X_test = np.array(X_test)

In [12]:
from __future__ import print_function
import keras
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
import os
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization
model = Sequential()
model.add(Conv2D(8, (2, 2), padding='same', input_shape=X_train.shape[1:])) 
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(12))
model.add(Activation('softmax'))

ResourceExhaustedError: ignored

In [ ]:
from tensorflow import keras
import tensorflow as tf
model.compile(loss='categorical_crossentropy',
              optimizer= tf.keras.optimizers.Adam(),
              metrics=['accuracy'])


X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

model.fit(X_train, y_train,
            batch_size= 64,
            epochs=20,
            validation_split = 0.2,
              shuffle=True)

In [ ]:
X_train[0]

In [ ]:
y.shape

In [ ]:
X[0].shape